### PR TITLE
U ptemp

### PR DESCRIPTION
**Pull request by vartom**
Try these patches. fix build warnings
 In Geekbench 1999/3460 at 2.295 Ghz.

### CODE REVIEW

**Comment by USBhost** [comment]
thanks i will merge it after some testing

**Comment by USBhost** [comment]
https://github.com/USBhost/FIRE-ICE/tree/vartom-UPtemp

When i have time i will go through everything you did so i know where your going with it.
keep doing what your doing and thanks for helping!

**Comment by USBhost** [comment]
@vartom Hey man! to give you an update Im currently merging l4t-r23.2 into the stock kernel
and Im 1k/12k of commits done. i will try to do 1k a day so i should have it done by this month. when i am done the chances of it booting are about 10-20% high so wish me luck! if that fails then i will use what you have done!

**Comment by vartom** [comment]
Hello! Good luck!
I'm in their endeavors to patch the GPU began to get stuck. A higher differences in the kernel. Everything is going to return to the kernel (or part thereof) in April 2014. Just I tried to add a parallel board Flounder on a modern kernel for Shield. So far without success because I can not dock the added audio codecs and sensors. https://github.com/vartom/android_kernel_nvidia_shieldtablet/commits/cm-13+v

**Comment by USBhost** [comment]
Merged into 10.4.y

**Pull request closed without merging**
